workflows:
  web-app:
    name: Build and Deploy to Firebase Hosting
    environment:
      groups:
        - firebase-auth
      vars:
        GOOGLE_APPLICATION_CREDENTIALS: $CM_BUILD_DIR/service-account.json
        FIREBASE_PROJECT_ID: "project-6349879156933445469"
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build the web app
        script: |
          npm run build
      - name: Verify build output
        script: |
          ls -lh build
      - name: Decode Firebase Credentials
        script: |
          echo $FIREBASE_AUTH_CREDENTIALS | base64 --decode > $CM_BUILD_DIR/service-account.json
      - name: Deploy to Firebase Hosting
        script: |
          firebase deploy --only hosting --project $FIREBASE_PROJECT_ID --token $FIREBASE_AUTH_TOKEN
    artifacts:
      - build/**/*








