workflows:
  fullstack-app:
    name: Build and Notify via Email
    environment:
      vars:
        EMAIL_RECIPIENTS: "cyl233master@gmail.com"  # 测试人员的邮箱列表，多个邮箱用逗号分隔
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build the app
        script: |
          npm run build
      - name: Notify testers via email
        script: |
          if [ -d ./build ]; then
            echo "Build successful! The latest build is ready for testing. Download it from Codemagic." | mail -s "Build Successful" $EMAIL_RECIPIENTS
          else
            echo "Build failed! Please check the logs for more details." | mail -s "Build Failed" $EMAIL_RECIPIENTS
          fi
    artifacts:
      - build/**/*  # 构建生成的文件






