workflows:
  fullstack-app:
    name: Build, Test, and Distribute Fullstack App
    max_build_duration: 30
    environment:
      vars:
        NODE_VERSION: 16.13.0
        FIREBASE_APP_ID: 1:842998708167:web:b9b1a38ee400975807cbe2
        GOOGLE_APPLICATION_CREDENTIALS: $CM_BUILD_DIR/firebase_credentials.json
    scripts:
      - name: Install Firebase CLI
        script: |
          curl -sL https://firebase.tools | bash
      - name: Save Firebase Credentials
        script: |
          echo "$FIREBASE_AUTH_CREDENTIALS" > $GOOGLE_APPLICATION_CREDENTIALS
      - name: Install dependencies
        script: |
          npm install
      - name: Build the app
        script: |
          npm run build
      - name: Upload to Firebase App Distribution
        script: |
          firebase appdistribution:distribute ./build/app-release.apk \
          --app $FIREBASE_APP_ID \
          --testers cyl233master@gmail.com
    artifacts:
      - build/**/*

