- name: Send email notification via SendGrid
  script: |
    curl --request POST \
    --url https://api.sendgrid.com/v3/mail/send \
    --header "Authorization: Bearer YOUR_SENDGRID_API_KEY" \
    --header "Content-Type: application/json" \
    --data '{
      "personalizations": [
        {
          "to": [{"email": "cyl233master@gmail.com"}],
          "subject": "Build Successful"
        }
      ],
      "from": {"email": "your-email@example.com"},
      "content": [{"type": "text/plain", "value": "The latest build is ready for testing."}]
    }'







