workflows:
  fullstack-app:
    name: Build and Deploy Fullstack App
    environment:
      vars:
        NODE_VERSION: 16.13.0
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build the app
        script: |
          ./gradlew assembleRelease
      - name: Upload to Firebase App Distribution
        script: |
          echo "$FIREBASE_AUTH_CREDENTIALS" | base64 --decode > /tmp/firebase-credentials.json
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/firebase-credentials.json
          firebase appdistribution:distribute ./app/build/outputs/apk/release/app-release.apk \
            --app 1:842998708167:web:b9b1a38ee400975807cbe2
    artifacts:
      - app/build/outputs/apk/release/app-release.apk




