workflows:
  fullstack-app:
    name: Build and Notify via Gmail
    environment:
      vars:
        EMAIL_RECIPIENTS: "gs70696@student.upm.edu.my"
        SMTP_SERVER: "smtp.gmail.com"
        SMTP_PORT: "587"
        SMTP_USER: "cyl233master@gmail.com"
        SMTP_PASSWORD: "cyl1998316"  # 需要生成 Gmail 应用密码
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build the app
        script: |
          npm run build
      - name: Send email notification via Gmail
        script: |
          echo -e "Subject: Build Successful\n\nThe latest build is ready for testing." | \
          curl --url "smtp://$SMTP_SERVER:$SMTP_PORT" --ssl-reqd \
               --mail-from "$SMTP_USER" --mail-rcpt "$EMAIL_RECIPIENTS" \
               --user "$SMTP_USER:$SMTP_PASSWORD" \
               --upload-file -







