workflows:
  fullstack-app:
    name: Build and Notify via Email
    environment:
      vars:
        EMAIL_RECIPIENTS: "cyl233master@gmail.com"  # 测试人员邮箱
    scripts:
      - name: Install mailutils
        script: |
          brew update
          brew install mailutils
      - name: Install dependencies
        script: |
          npm install
      - name: Build the app
        script: |
          npm run build
      - name: Notify testers via email
        script: |
          if [ -d ./build ]; then
            echo "Build successful! The latest build is ready for testing. Download it from Codemagic." | mail -s "Build Successful" $EMAIL_RECIPIENTS
          else
            echo "Build failed! Please check the logs for more details." | mail -s "Build Failed" $EMAIL_RECIPIENTS
          fi
    artifacts:
      - build/**/*







