workflows:
  fullstack-app:
    name: Build and Deploy to Firebase Hosting
    environment:
      groups:
        - firebase-auth  # 确保 Codemagic 变量组里包含 FIREBASE_AUTH_CREDENTIALS
      vars:
        GOOGLE_APPLICATION_CREDENTIALS: $CM_BUILD_DIR/service-account.json  # 设置 Firebase 认证文件路径
        FIREBASE_PROJECT_ID: "project-6349879156933445469"  # 你的 Firebase 项目 ID
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build the web app
        script: |
          npm run build
      - name: Decode Firebase Credentials
        script: |
          echo $FIREBASE_AUTH_CREDENTIALS | base64 --decode > $CM_BUILD_DIR/service-account.json
      - name: Deploy to Firebase Hosting
        script: |
          firebase deploy --only hosting --project $FIREBASE_PROJECT_ID --token $FIREBASE_AUTH_TOKEN
    artifacts:
      - build/**/*






