workflows:
  fullstack-app:
    name: Build and Deploy Fullstack App
    max_build_duration: 30
    environment:
      vars:
        NODE_VERSION: 16.13.0
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build the app
        script: |
          npm run build
    artifacts:
      - build/**/*
